version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /cmd/controller
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /cmd/machine-agent
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /deploy/daprd
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
