version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 4
    labels:
      - dependencies
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 4
    labels:
      - dependencies
    groups:
      go-modules:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 4
    labels:
      - dependencies
    groups:
      npm-production:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
      npm-development:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production-major:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - major
      npm-development-major:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - major

  - package-ecosystem: docker
    directory: /cmd/controller
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 4
    labels:
      - dependencies
    groups:
      controller-images:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /cmd/machine-agent
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 4
    labels:
      - dependencies
    groups:
      machine-agent-images:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /deploy/daprd
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 4
    labels:
      - dependencies
    groups:
      daprd-images:
        applies-to: version-updates
        patterns:
          - "*"
