---
stages:
  - validate
  - test
  - build
  - plan
  - deploy
  - cleanup

variables:
    TF_VAR_controller_image: ${TF_VAR_region}-docker.pkg.dev/${TF_VAR_project_id}/metio/controller:$CI_COMMIT_SHORT_SHA
    TF_VAR_machine_agent_image: ${TF_VAR_region}-docker.pkg.dev/${TF_VAR_project_id}/metio/machine-agent:$CI_COMMIT_SHORT_SHA

build-controller:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    stage: build
    script:
      - source .gitlab/ci/setup-application-credentials.sh
      - gcloud builds submit . --config cmd/controller/cloudbuild.yaml --region europe-west3 --substitutions=COMMIT_SHA=$CI_COMMIT_SHORT_SHA
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      - if: $CI_OPEN_MERGE_REQUESTS
        when: never
      - if: $CI_COMMIT_BRANCH

build-machine-agent:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    stage: build
    script:
      - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      - gcloud builds submit . --config cmd/machine-agent/cloudbuild.yaml --region europe-west3 --substitutions=COMMIT_SHA=$CI_COMMIT_SHORT_SHA
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      - if: $CI_OPEN_MERGE_REQUESTS
        when: never
      - if: $CI_COMMIT_BRANCH

include:
   - component: $CI_SERVER_FQDN/components/opentofu/full-pipeline@3.0.1
     inputs:
      root_dir: cloud/
      auto_define_backend: true
      state_name: $CI_COMMIT_REF_SLUG
      enable_id_tokens: true
      stage_build: plan
      apply_rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
          when: never
        - if: $CI_COMMIT_BRANCH        # If there's no open merge request, add it to a *branch* pipeline instead.
      destroy_rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: never
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
          when: never
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          when: manual
      delete_state_rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          when: never
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_OPEN_MERGE_REQUESTS  # Don't add it to a *branch* pipeline if it's already in a merge request pipeline.
          when: never
        - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
          when: manual
.gitlab-tofu:id_tokens:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
