steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-f', 'cmd/mc-backup/Dockerfile', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/metio/mc-backup:$COMMIT_SHA']
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/metio/mc-backup:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY