apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v2
  metadata:
    - name: connectionString
      secretKeyRef:
        name: postgres-connection-string
        key: postgres-connection-string
auth:
  secretStore: local-secret-file
